routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\VulnerabilityController;

Route::get('/', [DashboardController::class, 'index'])->name('dashboard.index');
Route::resource('vulnerabilities', VulnerabilityController::class);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/Vulnerability.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Vulnerability extends Model
{
    use HasFactory;

    protected $fillable = [
        'slug',
        'title',
        'description',
        'overview',
        'how_to_prevent',
    ];

    protected static function booted()
    {
        static::created(function (Vulnerability $vulnerability) {
            $vulnerability->slug = Str::slug($vulnerability->title);
            $vulnerability->save();
        });
    }

    public function getAttribute($key): string
    {
        if ((array_key_exists($key, $this->attributes) || $this->hasGetMutator($key))
            && (request()->routeIs('vulnerabilities.index'))) {
            if ($key !== 'slug') {
                return Str::limit($this->getAttributeValue($key), 20);
            }
        }

        return $this->getAttributeValue($key);
    }

    public function getRouteKeyName(): string
    {
        return 'slug';
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('dashboard.index');
    }
}

app/Http/Controllers/VulnerabilityController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\VulnerabilityRequest;
use App\Models\Vulnerability;

class VulnerabilityController extends Controller
{
    public function index()
    {
        $vulnerabilities = Vulnerability::query()
            ->orderBy('created_at', 'DESC')
            ->paginate(10);

        return view('vulnerabilities.index', compact('vulnerabilities'));
    }

    public function show(Vulnerability $vulnerability)
    {
        return view('vulnerabilities.show', compact('vulnerability'));
    }

    public function create()
    {
        return view('vulnerabilities.create');
    }

    public function store(VulnerabilityRequest $request)
    {
        $vulnerability = Vulnerability::query()->create($request->all());

        return redirect()->route('vulnerabilities.edit', $vulnerability)
            ->with(['message' => 'Vulnerability Created!']);
    }

    public function edit(Vulnerability $vulnerability)
    {
        return view('vulnerabilities.edit', compact('vulnerability'));
    }

    public function update(VulnerabilityRequest $request, Vulnerability $vulnerability)
    {
        $vulnerability->update($request->all());

        return redirect()->route('vulnerabilities.edit', $vulnerability)
            ->with(['message' => 'Vulnerability Updated!']);
    }

    public function destroy(Vulnerability $vulnerability)
    {
        $vulnerability->delete();

        return redirect()->route('vulnerabilities.index')
            ->with(['message' => 'Vulnerability Deleted!']);
    }
}

resources/views/dashboard/index.blade.php
<x-app-layouts>
    <x-slot name="title">Dashboard</x-slot>
    <div class="py-6">
        Super cool reports here.
    </div>
</x-app-layouts>

resources/views/layouts/_includes/sidebar-desktop.blade.php
<div class="hidden md:flex md:w-64 md:flex-col md:fixed md:inset-y-0">
    <!-- Sidebar component, swap this element with another sidebar if you like -->
    <div class="flex flex-col flex-grow pt-5 bg-indigo-700 overflow-y-auto">
        <div class="flex items-center flex-shrink-0 px-4">
            <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-logo-indigo-300-mark-white-text.svg" alt="Workflow">
        </div>
        <div class="mt-5 flex-1 flex flex-col">
            <nav class="flex-1 px-2 pb-4 space-y-1">
                <!-- Current: "bg-indigo-800 text-white", Default: "text-indigo-100 hover:bg-indigo-600" -->
                <a href="{{ route('dashboard.index') }}" class="{{ request()->routeIs('dashboard.*') ? 'bg-indigo-800' : '' }} text-white group flex items-center px-2 py-2 text-sm font-medium rounded-md">
                    <!-- Heroicon name: outline/home -->
                    <svg class="mr-3 flex-shrink-0 h-6 w-6 text-indigo-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
                    </svg>
                    {{ __('Dashboard') }}
                </a>

                <a href="{{ route('vulnerabilities.index') }}" class="{{ request()->routeIs('vulnerabilities.*') ? 'bg-indigo-800' : '' }} text-indigo-100 hover:bg-indigo-600 group flex items-center px-2 py-2 text-sm font-medium rounded-md">
                    <!-- Heroicon name: outline/users -->
                    <svg class="mr-3 flex-shrink-0 h-6 w-6 text-indigo-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
                    </svg>
                    {{ __('Vulnerabilities') }}
                </a>
            </nav>
        </div>
    </div>
</div>

resources/views/layouts/_includes/sidebar-mobile.blade.php
<div x-cloack x-data="{ open: true }" x-show="open" class="fixed inset-0 flex z-40 md:hidden" role="dialog" aria-modal="true">
    <div class="fixed inset-0 bg-gray-600 bg-opacity-75" aria-hidden="true"></div>
    <div class="relative flex-1 flex flex-col max-w-xs w-full pt-5 pb-4 bg-indigo-700">
        <div class="absolute top-0 right-0 -mr-12 pt-2">
            <button @click="open = false" type="button" class="ml-1 flex items-center justify-center h-10 w-10 rounded-full focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white">
                <span class="sr-only">Close sidebar</span>
                <!-- Heroicon name: outline/x -->
                <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
            </button>
        </div>

        <div class="flex-shrink-0 flex items-center px-4">
            <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-logo-indigo-300-mark-white-text.svg" alt="Workflow">
        </div>
        <div class="mt-5 flex-1 h-0 overflow-y-auto">
            <nav class="px-2 space-y-1">
                <!-- Current: "bg-indigo-800 text-white", Default: "text-indigo-100 hover:bg-indigo-600" -->
                <a href="{{ route('dashboard.index') }}" class="{{ request()->routeIs('dashboard.*') ? 'bg-indigo-800' : '' }} text-white group flex items-center px-2 py-2 text-base font-medium rounded-md">
                    <!-- Heroicon name: outline/home -->
                    <svg class="mr-4 flex-shrink-0 h-6 w-6 text-indigo-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
                    </svg>
                    {{ __('Dashboard') }}
                </a>

                <a href="{{ route('vulnerabilities.index') }}" class="{{ request()->routeIs('vulnerabilities.*') ? 'bg-indigo-800' : '' }} text-indigo-100 hover:bg-indigo-600 group flex items-center px-2 py-2 text-base font-medium rounded-md">
                    <!-- Heroicon name: outline/users -->
                    <svg class="mr-4 flex-shrink-0 h-6 w-6 text-indigo-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
                    </svg>
                    {{ __('Vulnerabilities') }}
                </a>
            </nav>
        </div>
    </div>

    <div class="flex-shrink-0 w-14" aria-hidden="true">
        <!-- Dummy element to force sidebar to shrink to fit close icon -->
    </div>
</div>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Vulnerabilities CRUD</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/@tailwindcss/typography@0.4.x/dist/typography.min.css" />
    <link rel="stylesheet" href="https://unpkg.com/@tailwindcss/custom-forms@0.2.1/dist/custom-forms.min.css" />
    <script defer src="https://unpkg.com/alpinejs@3.5.1/dist/cdn.min.js"></script>
    @stack('styles')
    <style>
        [x-cloack] {
            display: none;
        }
    </style>
</head>
<body>
<div>
    <!-- Static sidebar for mobile -->
    @include('layouts._includes.sidebar-mobile')

    <!-- Static sidebar for desktop -->
    @include('layouts._includes.sidebar-desktop')

    <div class="md:pl-64 flex flex-col flex-1">
        @if(session()->get('message'))
            <x-alert message="{{ session('message') }}" />
        @endif
        <main>
            <div class="py-6">
                <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">
                    <h1 class="text-2xl font-semibold text-gray-900">{{ $title }}</h1>
                </div>
                <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">
                    {{ $slot }}
                </div>
            </div>
        </main>
    </div>
</div>
@stack('scripts')
</body>
</html>

resources/views/vulnerabilities/_includes/fields.blade.php
<div class="mt-6 sm:mt-5 space-y-6">
    <x-input.group label="Title" for="title" :error="$errors->first('title')">
        <x-input.text name="title" id="title" value="{{ isset($vulnerability) ? $vulnerability->title : old('title') }}" />
    </x-input.group>
    <x-input.group label="Overview" for="overview" :error="$errors->first('overview')" help-text="Write a overview on a vulnerability.">
        <x-input.rich-text name="overview" id="overview" value="{{ isset($vulnerability) ? $vulnerability->overview : old('overview') }}" />
    </x-input.group>
</div>
<x-input.group label="Description" for="description" :error="$errors->first('description')" help-text="Write a vulnerability description">
    <x-input.rich-text name="description" id="description" value="{{ isset($vulnerability) ? $vulnerability->description : old('description') }}" />
</x-input.group>

<x-input.group label="How To Prevent" for="how_to_prevent" :error="$errors->first('how_to_prevent')" help-text="Write a how to prevent a vulnerability">
    <x-input.rich-text name="how_to_prevent" id="how_to_prevent" value="{{ isset($vulnerability) ? $vulnerability->how_to_prevent : old('how_to_prevent') }}" />
</x-input.group>

<div class="flex justify-end">
    <span class="inline-flex rounded-md shadow-sm">
        <a href="{{ route('vulnerabilities.index') }}" class="py-2 px-4 border border-gray-300 rounded-md text-sm leading-5 font-medium text-gray-700 hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-50 active:text-gray-800 transition duration-150 ease-in-out">
            {{ __('Cancel') }}
        </a>
    </span>

    <span class="ml-3 inline-flex rounded-md shadow-sm">
        <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition duration-150 ease-in-out">
            {{ __('Save') }}
        </button>
    </span>
</div>

resources/views/vulnerabilities/create.blade.php
<x-app-layouts>
    <x-slot name="title">{{ __('Create New Vulnerability') }}</x-slot>
    <form action="{{ route('vulnerabilities.store') }}" method="POST">
        @csrf
        @include('vulnerabilities._includes.fields')
    </form>
</x-app-layouts>

resources/views/vulnerabilities/edit.blade.php
<x-app-layouts>
    <x-slot name="title">{{ __("Edit Vulnerability - $vulnerability->title") }}</x-slot>
    <form action="{{ route('vulnerabilities.update', $vulnerability) }}" method="POST">
        @csrf
        @method('PUT')
        @include('vulnerabilities._includes.fields')
    </form>
</x-app-layouts>

resources/views/vulnerabilities/index.blade.php
<x-app-layouts>

    <x-slot name="title">{{ __('Vulnerabilities') }}</x-slot>

    <div class="flex flex-col py-5">
        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="flex justify-end py-5">
                    <a href="{{ route('vulnerabilities.create') }}" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        {{ __('Create Vulnerability') }}
                    </a>
                </div>
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Title
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Description
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Overview
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                How To Prevent
                            </th>
                            <th scope="col" class="relative px-6 py-3">
                                <span class="sr-only">View</span>
                            </th>
                            <th scope="col" class="relative px-6 py-3">
                                <span class="sr-only">Edit</span>
                            </th>
                            <th scope="col" class="relative px-6 py-3">
                                <span class="sr-only">Delete</span>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($vulnerabilities as $vulnerability)
                            <tr class="{{ $loop->odd ? 'bg-white' : 'bg-gray-50' }}">
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    {{ $vulnerability->title }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    {{ $vulnerability->description }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    {{ $vulnerability->overview }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    {{ $vulnerability->how_to_prevent }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 underline hover:text-indigo-600">
                                    <a href="{{ route('vulnerabilities.show', $vulnerability) }}">
                                        {{ __('View') }}
                                    </a>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    <a href="{{ route('vulnerabilities.edit', $vulnerability) }}" class="text-indigo-600 hover:text-indigo-900">
                                        {{ __('Edit') }}
                                    </a>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    <form method="POST" action="{{ route('vulnerabilities.destroy', $vulnerability) }}">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="text-red-600 hover:text-indigo-900">
                                            {{ __('Delete') }}
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    No records yet...
                                </td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
                <div class="py-4">
                    {{ $vulnerabilities->links() }}
                </div>
            </div>
        </div>
    </div>
</x-app-layouts>

resources/views/vulnerabilities/show.blade.php
<x-app-layouts>
    <div class="py-6">
        <x-slot name="title">
            <a href="{{ route('vulnerabilities.index') }}" class="hover:text-indigo-600">
                {{ __('Vulnerabilities') }}
            </a>
            /
            {{ $vulnerability->title }}
        </x-slot>
    </div>
    <div class="relative bg-white">
        <div class="lg:absolute lg:inset-0">
            <div class="lg:absolute lg:inset-y-0 lg:left-0 lg:w-1/2">
                <img class="h-56 w-full object-cover rounded shadow-2xl lg:absolute lg:h-full" src="https://images.unsplash.com/photo-1522071820081-009f0129c71c?ixlib=rb-1.2.1&auto=format&fit=crop&w=1567&q=80" alt="">
            </div>
        </div>
        <div class="relative pt-12 pb-16 px-4 sm:pt-16 sm:px-6 lg:px-8 lg:max-w-7xl lg:mx-auto lg:grid lg:grid-cols-2">
            <div class="lg:col-start-2 lg:pl-8">
                <div class="text-base max-w-prose mx-auto lg:max-w-lg lg:ml-auto lg:mr-0">
                    <h2 class="leading-6 text-indigo-600 font-semibold tracking-wide uppercase">{{ __('Vulnerability Category') }}</h2>
                    <h3 class="mt-2 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">{{ $vulnerability->title }}</h3>
                    <div class="mt-5 prose prose-indigo text-gray-500">
                        <h3>{{ __('Overview') }}</h3>
                        <p class="mt-8 text-lg text-gray-500">{!! $vulnerability->overview !!} </p>
                    </div>
                    <div class="mt-5 prose prose-indigo text-gray-500">
                        <h3>{{ __('Description') }}</h3>
                        {!! $vulnerability->description !!}
                    </div>
                    <div class="mt-5 prose prose-indigo text-gray-500">
                        <h3>{{ __('How To Prevent') }}</h3>
                        <p>{!! $vulnerability->how_to_prevent !!}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layouts>